Repository DataDog/system-tests, pull requests merged in 2023-05, with the labels that each got.

#1012 Add Vert.x 4.x support for java
  .github/workflows/ci.yml
  tests/appsec/test_endpoint_ognl.py
  tests/appsec/test_endpoint_sqli.py
  tests/appsec/waf/test_addresses.py
  tests/test_scrubbing.py
  tests/test_semantic_conventions.py
  utils/build/docker/java/vertx4.Dockerfile
  utils/build/docker/java/vertx4/pom.xml
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSourceRouteProvider.java
  utils/build/docker/java/vertx4/src/main/resources/logging.properties
Labels: java

#1134 telemetry(python): skip irrelevant app-dependencies-loaded validation
  tests/test_telemetry.py
Labels: run-default-scenario

#1141 Add pyenv .python-version to .gitignore
  .gitignore
Labels: run-default-scenario

#1145 [onboarding] fix rpm and debian dd beta repos
  onboarding/autoinjection/repositories/rpm/datadog-staging.repo
  onboarding/autoinjection/yaml/includes/provision_prepare_repos.yml
Labels: run-default-scenario

#1129 Refactor IAST sink tests
  tests/appsec/iast/iast_fixtures.py
  tests/appsec/iast/sink/test_command_injection.py
  tests/appsec/iast/sink/test_iast_command_injection.py
  tests/appsec/iast/sink/test_iast_ldap_injection.py
  tests/appsec/iast/sink/test_iast_path_traversal.py
  tests/appsec/iast/sink/test_iast_sql_injection.py
  tests/appsec/iast/sink/test_iast_weak_cipher.py
  tests/appsec/iast/sink/test_ldap_injection.py
  tests/appsec/iast/sink/test_path_traversal.py
  tests/appsec/iast/sink/test_sql_injection.py
  tests/appsec/iast/sink/test_weak_cipher.py
  tests/appsec/iast/sink/test_weak_hash.py
Labels: run-default-scenario

#1147 Remove unused test_miscs.py
  tests/appsec/test_miscs.py
Labels: run-default-scenario

#1101 [parametric/dotnet] don't skip 128-bit trace id tests
  parametric/apps/dotnet/ApmTestClient.csproj
  parametric/test_128_bit_traceids.py
Labels: dotnet

#1154 Fix telemetry test (uniquely identify requests)
  tests/test_telemetry.py
Labels: run-default-scenario

#1133 Add set of scenario feature
  run.sh
  utils/_context/_scenarios.py
Labels: run-default-scenario, dev-x

#1163 Remove library versions for Test_Basic
  tests/test_miscs.py
Labels: run-default-scenario

#1165 Update scenario sets
  run.sh
Labels: run-default-scenario, dev-x

#1159 SSRF vulnerabiilty detection system test implemented in nodejs and java
  tests/appsec/iast/sink/test_ssrf.py
  utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/SsrfExamples.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
  utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
  utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
  utils/build/docker/nodejs/express4/iast.js
Labels: run-default-scenario

#1171 update nodejs system tests to use v16
  utils/build/docker/nodejs/express4-typescript.Dockerfile
  utils/build/docker/nodejs/express4.Dockerfile
  utils/build/docker/nodejs/uds-express4.Dockerfile
Labels: run-default-scenario

#1161 [parametric] fix test, don't require "t.tid" in "tracestate" W3C header
  parametric/test_headers_tracestate_dd.py
Labels: bug, run-default-scenario

#1174 Rename TestIastWeakCipher to TestWeakCipher
  tests/appsec/iast/sink/test_weak_cipher.py
Labels: run-default-scenario

#1175 Fix SinkFixture.test_secure test
  tests/appsec/iast/iast_fixtures.py
Labels: run-default-scenario

#1180 [opentelemetry] Allow to configure which path to include
  .github/workflows/ci.yml
  tests/otel_tracing_e2e/_validator.py
  tests/otel_tracing_e2e/test_e2e.py
  utils/_context/_scenarios.py
  utils/build/docker/java_otel/spring-boot-native/src/main/java/com/datadoghq/springbootnative/App.java
  utils/build/docker/java_otel/spring-boot-native/src/main/java/com/datadoghq/springbootnative/WebController.java
Labels: opentelemetry

#1169 Add a mode that replay tests based on logs
  .github/workflows/ci.yml
  .gitignore
  conftest.py
  tests/appsec/test_blocking_addresses.py
  tests/appsec/test_logs.py
  tests/fuzzer/main.py
  tests/integrations/test_dsm.py
  tests/test_the_test/test_stdout_reader.py
  utils/_context/_scenarios.py
  utils/_context/containers.py
  utils/_weblog.py
  utils/interfaces/_backend.py
  utils/interfaces/_core.py
  utils/interfaces/_logs.py
Labels: dev-x

#1181 IAST unvalidated redirect vulnerability
  tests/appsec/iast/sink/test_unvalidated_redirect.py
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
Labels: java, run-default-scenario

#1184 Documentation on replay mode
  docs/execute/replay.md
  utils/assets/replay.png
Labels: run-default-scenario, dev-x

#1064 Test akka-http
  .github/workflows/ci.yml
  tests/appsec/iast/sink/test_command_injection.py
  tests/appsec/iast/sink/test_ldap_injection.py
  tests/appsec/iast/sink/test_path_traversal.py
  tests/appsec/iast/sink/test_sql_injection.py
  tests/appsec/iast/sink/test_weak_cipher.py
  tests/appsec/iast/sink/test_weak_hash.py
  tests/appsec/iast/source/test_body.py
  tests/appsec/iast/source/test_cookie_name.py
  tests/appsec/iast/source/test_cookie_value.py
  tests/appsec/iast/source/test_header_name.py
  tests/appsec/iast/source/test_header_value.py
  tests/appsec/iast/source/test_parameter_name.py
  tests/appsec/iast/source/test_parameter_value.py
  tests/appsec/test_alpha.py
  tests/appsec/test_conf.py
  tests/appsec/test_customconf.py
  tests/appsec/test_endpoint_ognl.py
  tests/appsec/test_endpoint_sqli.py
  tests/appsec/test_logs.py
  tests/appsec/test_rate_limiter.py
  tests/appsec/test_reports.py
  tests/appsec/test_runtime_activation.py
  tests/appsec/test_traces.py
  tests/appsec/waf/test_addresses.py
  tests/appsec/waf/test_blocking.py
  tests/appsec/waf/test_exclusions.py
  tests/appsec/waf/test_miscs.py
  tests/appsec/waf/test_reports.py
  tests/appsec/waf/test_rules.py
  tests/appsec/waf/test_telemetry.py
  tests/test_scrubbing.py
  tests/test_semantic_conventions.py
  tests/test_standard_tags.py
  utils/build/docker/java/akka-http.Dockerfile
  utils/build/docker/java/akka-http/.gitignore
  utils/build/docker/java/akka-http/pom.xml
  utils/build/docker/java/akka-http/src/main/resources/logback.xml
  utils/build/docker/java/akka-http/src/main/resources/reference.conf
  utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala
  utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/Main.scala
  utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/package.scala
Labels: java

#1183 Add weak randomness detection tests
  tests/appsec/iast/sink/test_weak_randomness.py
  utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/WeakRandomnessExamples.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
  utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
  utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
Labels: run-default-scenario

#1201 activate more tests for custom rules on python
  tests/appsec/waf/test_custom_rules.py
  tests/appsec/waf/test_exclusions.py
Labels: run-default-scenario

#1202 Fix old way to install parametric test
  .github/workflows/parametric.yml
  parametric/requirements.txt
  requirements.txt
  utils/interfaces/schemas/library/telemetry-request.json
Labels: run-default-scenario

#1213 Fix decorators for IAST SSRF test
  tests/appsec/iast/sink/test_ssrf.py
Labels: run-default-scenario

#1216 Add tracer teams as owners of weblog variants
  .github/CODEOWNERS
Labels: run-default-scenario

#1211 Remove iast conf from node test application to use env vars
  utils/build/docker/nodejs/express4/app.js
Labels: run-default-scenario

#1212 Enable telemetry heartbeat test
  tests/test_telemetry.py
Labels: run-default-scenario

#1220 Remove spring-boot-native weblog
  .github/workflows/ci.yml
  tests/appsec/iast/sink/test_command_injection.py
  tests/appsec/iast/sink/test_ldap_injection.py
  tests/appsec/iast/sink/test_path_traversal.py
  tests/appsec/iast/sink/test_sql_injection.py
  tests/appsec/iast/sink/test_ssrf.py
  tests/appsec/iast/sink/test_weak_cipher.py
  tests/appsec/iast/sink/test_weak_hash.py
  tests/appsec/test_alpha.py
  tests/appsec/test_conf.py
  tests/appsec/test_customconf.py
  tests/appsec/test_docs.py
  tests/appsec/test_endpoint_ognl.py
  tests/appsec/test_endpoint_sqli.py
  tests/appsec/test_logs.py
  tests/appsec/test_rate_limiter.py
  tests/appsec/test_reports.py
  tests/appsec/test_runtime_activation.py
  tests/appsec/test_traces.py
  tests/appsec/waf/test_addresses.py
  tests/appsec/waf/test_blocking.py
  tests/appsec/waf/test_exclusions.py
  tests/appsec/waf/test_miscs.py
  tests/appsec/waf/test_reports.py
  tests/appsec/waf/test_rules.py
  tests/appsec/waf/test_telemetry.py
  tests/remote_config/test_remote_configuration.py
  tests/test_semantic_conventions.py
  tests/test_standard_tags.py
  tests/test_telemetry.py
  utils/build/docker/java/spring-boot-native.Dockerfile
  utils/build/docker/java/spring-boot/pom.xml
Labels: java, test_the_tests, run-default-scenario

#1219 Unify jersey-grizzly2 and resteasy-netty3 weblogs
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSourceResource.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
  utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
Labels: java, test_the_tests, test_java
