Repository DataDog/system-tests, pull requests merged in 2023-07, with the labels that each got.

#1327 Test if telemetry heartbeats are sent too fast
  tests/test_telemetry.py
Labels: run-default-scenario

#1328 Extend telemetry app-started tests
  tests/test_telemetry.py
Labels: run-default-scenario

#1288 Automated user events milestone 1
  .github/workflows/ci.yml
  tests/appsec/test_automated_login_events.py
  utils/_context/_scenarios.py
Labels: run-all-scenarios

#1314 Remove redundancy in telemetry activation
  tests/test_telemetry.py
  utils/build/docker/set-system-tests-weblog-env.Dockerfile
Labels: run-all-scenarios

#1316 Added vulnerable cookie endpoints and enabled tests.
  tests/appsec/iast/sink/test_insecure_cookie.py
  tests/appsec/iast/sink/test_no_httponly_cookie.py
  tests/appsec/iast/sink/test_no_samesite_cookie.py
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
  utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
  utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
Labels: java

#1332 Skip Appsec rate limiter test on rails 5.1
  tests/appsec/test_rate_limiter.py
Labels: run-all-scenarios

#1293 Add IAST XPath injection system test
  tests/appsec/iast/sink/test_xpath_injection.py
  utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala
  utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/XPathExamples.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
  utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
  utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
Labels: java, run-default-scenario

#1333 Update parametric tests for Java tracer and OTel test suite
  tests/parametric/conftest.py
  tests/parametric/test_otel_span_methods.py
  tests/parametric/test_otel_span_with_w3c.py
  utils/build/docker/java/parametric/.gitignore
  utils/build/docker/java/parametric/Dockerfile
  utils/build/docker/java/parametric/pom.xml
Labels: java, run-all-scenarios

#1336 Remove some ingestion leftovers
  utils/interfaces/_backend.py
  utils/interfaces/_core.py
Labels: run-all-scenarios

#1296 Live Debugger test scenarios
  .github/workflows/ci.yml
  docs/weblog/README.md
  run.sh
  tests/debugger/test_debugger.py
  utils/_context/_scenarios.py
  utils/build/docker/dotnet/Controllers/DebuggerController.cs
  utils/build/docker/dotnet/app.sh
  utils/proxy/core.py
  utils/proxy/debugger/base_rcm.json
  utils/proxy/debugger/base_signed.json
  utils/proxy/debugger/base_target.json
  utils/proxy/rc_debugger.py
  utils/proxy/rc_mocked_responses_debugger_line_probes_status.json
  utils/proxy/rc_mocked_responses_debugger_method_probes_status.json
Labels: run-all-scenarios

#1337 Fix /etc/otelcol-config.yml perms in Linux
  utils/_context/containers.py
Labels: run-open-telemetry-scenarios

#1346 Improve E2E tests documentation
  docs/execute/e2e.md
Labels: documentation

#1325 onboarding 0.10.2
  .gitlab-ci.yml
  requirements.txt
  tests/onboarding/autoinjection/host_config.yaml
  tests/onboarding/autoinjection/repositories/autoinstall/execute_install_script_dev.sh
  tests/onboarding/infra_provision/provision_onboarding_container.yml
  tests/onboarding/infra_provision/provision_onboarding_host.yml
  tests/onboarding/infra_provision/provision_onboarding_host_container.yml
  tests/onboarding/weblog/dotnet/test-app-dotnet/test-app-dotnet.service
  tests/onboarding/weblog/java/test-app-java.service
  tests/onboarding/weblog/java/test-app-java/test-app-java copy.service
  tests/onboarding/weblog/java/test-app-java/test-app-java.service
  tests/onboarding/weblog/java/test-app-java/test-app-java_docker_compose_run_buildpack.sh
  tests/onboarding/weblog/java/wildfly/wildfly.service
  tests/onboarding/weblog/nodejs/test-app-nodejs/test-app-nodejs.service
  tests/onboarding/weblog/python/test-app-python-django/test-app-python.service
Labels: run-all-scenarios

#1334 Enable auto user events for nodejs v4.4.0
  tests/appsec/test_automated_login_events.py
  utils/build/docker/nodejs/express4-typescript.Dockerfile
  utils/build/docker/nodejs/express4-typescript/app.ts
  utils/build/docker/nodejs/express4-typescript/auth.ts
  utils/build/docker/nodejs/express4-typescript/package-lock.json
  utils/build/docker/nodejs/express4-typescript/package.json
Labels: run-all-scenarios

#1362 Fix id for extended tests as well
  tests/appsec/test_automated_login_events.py
  utils/build/docker/nodejs/express4/auth.js
Labels: run-all-scenarios

#1370 Skip flaky open-telemetry test
  tests/apm_tracing_e2e/test_otel.py
Labels: run-all-scenarios

#1377 java: Update deps (bcprov-jdk18on)
  utils/build/docker/java/akka-http/pom.xml
  utils/build/docker/java/iast-common/pom.xml
  utils/build/docker/java/vertx3/pom.xml
  utils/build/docker/java/vertx4/pom.xml
Labels: dependencies

#1379 Process to update images on hub.docker.com
  .github/pull_request_template.md
  .github/workflows/ci.yml
  docs/edit/update-docker-images.md
Labels: build-python-base-images, build-proxy-image

#1371 [dotnet] Activate user extended mode
  tests/appsec/test_automated_login_events.py
Labels: run-all-scenarios

#1372 Update rabbit tests in test_dsm.py for both Java and dotnet
  tests/integrations/test_dsm.py
  utils/build/docker/dotnet/Dependencies/RabbitMQHelper.cs
  utils/build/docker/dotnet/Endpoints/DsmEndpoint.cs
  utils/build/docker/dotnet/app.csproj
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnector.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnectorForDirectExchange.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnectorForFanoutExchange.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnectorForTopicExchange.java
Labels: run-all-scenarios

#1381 [GO] parametric: separated tracer initialisation for datadog and otel tests
  utils/build/docker/golang/parametric/datadog.go
  utils/build/docker/golang/parametric/main.go
  utils/build/docker/golang/parametric/otel.go
Labels: run-all-scenarios

#1342 Add missing IAST tests in Java
  tests/appsec/iast/sink/test_command_injection.py
  tests/appsec/iast/sink/test_ldap_injection.py
  tests/appsec/iast/sink/test_path_traversal.py
  tests/appsec/iast/sink/test_sql_injection.py
  tests/appsec/iast/sink/test_ssrf.py
  tests/appsec/iast/sink/test_unvalidated_redirect.py
  tests/appsec/iast/sink/test_unvalidated_redirect_forward.py
  tests/appsec/iast/sink/test_weak_cipher.py
  tests/appsec/iast/sink/test_weak_hash.py
  tests/appsec/iast/sink/test_weak_randomness.py
  tests/appsec/iast/sink/test_xpath_injection.py
  tests/appsec/iast/source/test_body.py
  tests/appsec/iast/source/test_cookie_name.py
  tests/appsec/iast/source/test_cookie_value.py
  tests/appsec/iast/source/test_header_name.py
  tests/appsec/iast/source/test_header_value.py
  tests/appsec/iast/source/test_parameter_name.py
  tests/appsec/iast/source/test_parameter_value.py
  utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala
  utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/XPathExamples.java
  utils/build/docker/java/jersey-grizzly2/pom.xml
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSourceResource.java
  utils/build/docker/java/ratpack.Dockerfile
  utils/build/docker/java/ratpack/pom.xml
  utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/IastHandlers.java
  utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
  utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSourceResource.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIastSource.java
  utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSourceRouteProvider.java
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSourceRouteProvider.java
Labels: java

#1366 go: enable custom blocking response test
  tests/appsec/waf/test_blocking.py
Labels: run-all-scenarios

#1396 Fix nodejs system-test
  utils/build/docker/nodejs/express4-typescript/auth.ts
  utils/build/docker/nodejs/express4/auth.js
  utils/build/docker/nodejs/express4/iast/index.js
Labels: run-all-scenarios

#1318 [opentelemetry] Allow to specify collector image
  utils/_context/containers.py
Labels: run-open-telemetry-scenarios

#1356 Dsm again
  tests/integrations/test_dsm.py
  utils/build/docker/nodejs/express4-typescript.Dockerfile
  utils/build/docker/nodejs/express4-typescript/app.ts
  utils/build/docker/nodejs/express4-typescript/package-lock.json
  utils/build/docker/nodejs/express4-typescript/package.json
  utils/build/docker/nodejs/express4.Dockerfile
  utils/build/docker/nodejs/express4/app.js
  utils/build/docker/nodejs/express4/package-lock.json
  utils/build/docker/nodejs/express4/package.json
  utils/build/docker/nodejs/uds-express4.Dockerfile
Labels: run-all-scenarios

#1402 Mitigate agent failure on dev tests
  utils/scripts/load-binary.sh
Labels: run-all-scenarios

#1412 Skip schema test on php/RC
  tests/remote_config/test_remote_configuration.py
Labels: run-all-scenarios

#1392 Investigate flaky tests
  .github/workflows/ci.yml
  tests/apm_tracing_e2e/test_otel.py
  tests/appsec/waf/test_telemetry.py
  tests/test_telemetry.py
  utils/_context/_scenarios.py
  utils/_context/containers.py
  utils/interfaces/_core.py
Labels: run-all-scenarios, run-open-telemetry-scenarios

#1409 Fix OTel collector healthcheck endpoint
  utils/_context/containers.py
Labels: run-open-telemetry-scenarios

#1395 Add automated login events tests to php
  tests/appsec/test_automated_login_events.py
  utils/build/docker/php/apache-mod/php.conf
  utils/build/docker/php/common/login.php
  utils/build/docker/php/php-fpm/php-fpm.conf
Labels: run-all-scenarios

#1411 Add support for message-batch (v2) payloads
  tests/appsec/waf/test_telemetry.py
  tests/test_telemetry.py
  utils/interfaces/_agent.py
  utils/interfaces/_library/core.py
Labels: run-all-scenarios

#1109 Dockerize runner
  .circleci/config.yml
  .dockerignore
  .github/actions/pull_images/action.yml
  .github/workflows/ci.yml
  .gitignore
  .shellcheck
  run.sh
  scenario_groups.yml
  utils/__init__.py
  utils/_context/_scenarios.py
  utils/_context/containers.py
  utils/_weblog.py
  utils/build/build.sh
  utils/build/docker/proxy.Dockerfile
  utils/build/docker/runner.Dockerfile
  utils/proxy/core.py
Labels: run-all-scenarios, build-proxy-image

#1423 Activate APPSEC Xpass tests
  tests/appsec/test_blocking_addresses.py
  tests/appsec/waf/test_addresses.py
  tests/appsec/waf/test_blocking.py
  tests/appsec/waf/test_custom_rules.py
  tests/appsec/waf/test_exclusions.py
Labels: run-all-scenarios

#1428 [APPSEC-10347] Add necessary code for automated login events in extended mode for ruby
  tests/appsec/test_automated_login_events.py
Labels: run-all-scenarios

#1418 Update DSM dotnet rabbit test's irrelevant condition
  tests/integrations/test_dsm.py
Labels: run-all-scenarios

#1353 feat(python): add iast source tests for python
  tests/appsec/iast/source/test_body.py
  tests/appsec/iast/source/test_cookie_name.py
  tests/appsec/iast/source/test_cookie_value.py
  tests/appsec/iast/source/test_header_name.py
  tests/appsec/iast/source/test_header_value.py
  tests/appsec/iast/source/test_parameter_name.py
  tests/appsec/iast/source/test_parameter_value.py
  utils/build/docker/python/django/django.app.urls.py
  utils/build/docker/python/flask/app.py
Labels: python

#1430 Prevent finding rid in non-service entry spans
  utils/interfaces/_core.py
Labels: run-all-scenarios

#1421 Update OpenTelemetry parametric tests for .NET
  tests/parametric/test_otel_span_methods.py
  tests/parametric/test_otel_span_with_w3c.py
  tests/parametric/test_otel_tracer.py
  utils/build/docker/dotnet/parametric/ApmTestClient.csproj
  utils/build/docker/dotnet/parametric/Services/ApmTestClientService.Otel.cs
Labels: run-parametric-scenario

#1435 Fix yaml parsing
  .github/workflows/ci.yml
  run.sh
  shell.nix
Labels: run-all-scenarios

#1447 Fix bug in telemetry `message-batch` support
  utils/interfaces/_library/core.py
Labels: bug, run-all-scenarios

#1442 Add library version detection for parametric tests
  tests/parametric/conftest.py
  tests/parametric/test_tracer.py
  utils/_context/_scenarios.py
Labels: run-parametric-scenario
