Repository DataDog/system-tests, pull requests merged in 2023-03, with the labels that each got.

#915 Update Docker images for Java to Temurin 11
  utils/build/docker/java/jersey-grizzly2.Dockerfile
  utils/build/docker/java/ratpack.Dockerfile
  utils/build/docker/java/resteasy-netty3.Dockerfile
  utils/build/docker/java/spring-boot-jetty.Dockerfile
  utils/build/docker/java/spring-boot-openliberty.Dockerfile
  utils/build/docker/java/spring-boot-undertow.Dockerfile
  utils/build/docker/java/spring-boot-wildfly.Dockerfile
  utils/build/docker/java/spring-boot.Dockerfile
  utils/build/docker/java/uds-spring-boot.Dockerfile
  utils/build/docker/java/vertx3.Dockerfile
Labels: java

#916 Simplify Java app.sh
  utils/build/docker/java/app.sh
  utils/build/docker/java/jersey-grizzly2.Dockerfile
  utils/build/docker/java/ratpack.Dockerfile
  utils/build/docker/java/resteasy-netty3.Dockerfile
  utils/build/docker/java/spring-boot-3-native.Dockerfile
  utils/build/docker/java/spring-boot-jetty.Dockerfile
  utils/build/docker/java/spring-boot-native.Dockerfile
  utils/build/docker/java/spring-boot-openliberty.Dockerfile
  utils/build/docker/java/spring-boot-undertow.Dockerfile
  utils/build/docker/java/spring-boot-wildfly.Dockerfile
  utils/build/docker/java/spring-boot.Dockerfile
  utils/build/docker/java/vertx3.Dockerfile
Labels: java, run-default-scenario

#923 fix the APM_TRACING_E2E scenario missing after migration of run.sh
  utils/_context/core.py
Labels: run-default-scenario

#914 Add more Java logging in parametric test client
  parametric/apps/java/pom.xml
  parametric/apps/java/run.sh
  parametric/apps/java/src/main/java/com/datadoghq/ApmClientImpl.java
  parametric/apps/java/src/main/java/com/datadoghq/App.java
  parametric/apps/java/src/main/resources/logback.xml
Labels: run-default-scenario

#922 Enable Java parametric tests in workflow
  .github/workflows/parametric.yml
  parametric/apps/java/pom.xml
  parametric/apps/java/src/main/java/com/datadoghq/ApmClientImpl.java
  parametric/test_headers_b3.py
  parametric/test_headers_b3multi.py
  parametric/test_headers_datadog.py
  parametric/test_headers_precedence.py
  parametric/test_headers_tracecontext.py
  parametric/test_headers_tracestate_dd.py
  parametric/utils/headers.py
  utils/scripts/generate-github-action-file.py
Labels: run-default-scenario

#929 Skip schema test for node tracer v2
  tests/test_schemas.py
Labels: run-default-scenario

#931 Fix backend typo
  utils/interfaces/_backend.py
Labels: run-default-scenario

#932 feat(python): update RC gunicorn behavior
  tests/remote_config/test_remote_configuration.py
Labels: run-default-scenario

#909 [parametric] Removes test skips for the header tests that are now passing
  parametric/conftest.py
  parametric/test_headers_b3.py
  parametric/test_headers_b3multi.py
  parametric/test_headers_datadog.py
  parametric/test_headers_none.py
  parametric/test_headers_precedence.py
  parametric/test_headers_tracecontext.py
  parametric/test_headers_tracestate_dd.py
Labels: run-default-scenario

#938 Enable Event Tracking tests in Java
  tests/appsec/test_event_tracking.py
  utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
Labels: java, run-default-scenario

#945 Enable Client-IP test for ruby. The test would work on the next release.
  tests/test_standard_tags.py
Labels: run-default-scenario

#944 Fix load_binary.sh for Java
  utils/scripts/load-binary.sh
Labels: run-default-scenario

#911 Aditi.maheshwari/telemetry dependency flag test
  tests/test_telemetry.py
  utils/interfaces/schemas/miscs/telemetry/common/events/dependencies-loaded.json
  utils/interfaces/schemas/miscs/telemetry/common/events/integrations-change.json
  utils/interfaces/schemas/miscs/telemetry/v2/events/extended-heartbeat.json
Labels: run-default-scenario

#939 Fix Telemetry v2 Schema References
  utils/interfaces/schemas/miscs/telemetry/v2/events/client-configuration-change.json
  utils/interfaces/schemas/miscs/telemetry/v2/events/extended-heartbeat.json
  utils/interfaces/schemas/miscs/telemetry/v2/events/message-batch.json
  utils/interfaces/schemas/miscs/telemetry/v2/objects/configuration.json
  utils/interfaces/schemas/miscs/telemetry/v2/telemetry_request.json
Labels: run-default-scenario

#956 update ruby version to the one that fixed the client IP extraction logic
  tests/test_standard_tags.py
Labels: run-default-scenario

#960 Fix v2 instrumentation telemetry json schema
  utils/interfaces/schemas/miscs/telemetry/v2/telemetry_request.json
Labels: run-default-scenario

#965 Fix skip condition on spring*native
  tests/appsec/test_event_tracking.py
Labels: run-default-scenario

#966 Add users endpoint on php
  utils/build/docker/php/common/users.php
Labels: run-default-scenario

#967 Disable telemetry flaky test
  tests/test_telemetry.py
Labels: run-default-scenario

#968 products array on remote config must not be empty
  utils/interfaces/schemas/library/v0.7/config-request.json
Labels: run-default-scenario

#971 Support for Linux aarch64
  utils/build/build.sh
Labels: run-default-scenario

#981 Use mitmproxy for the backend requests
  utils/_context/_scenarios.py
  utils/interfaces/_backend.py
  utils/interfaces/_core.py
  utils/proxy/core.py
Labels: run-default-scenario

#936 Add docs how to use a custom Java Tracer with parametric tests
  parametric/README.md
Labels: run-default-scenario

#982 Fixes for w3c test parametric tests
  parametric/test_headers_datadog.py
  parametric/test_headers_tracestate_dd.py
Labels: run-default-scenario

#964 Jersey grizzly IAST Tests
  tests/appsec/iast/sink/test_iast_command_injection.py
  tests/appsec/iast/sink/test_iast_path_traversal.py
  tests/appsec/iast/sink/test_iast_sql_injection.py
  tests/appsec/iast/sink/test_iast_weak_cipher.py
  tests/appsec/iast/sink/test_iast_weak_hash.py
  tests/appsec/iast/source/test_iast_request_cookie_name.py
  utils/build/docker/java/jersey-grizzly2/pom.xml
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/CmdExamples.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/CryptoExamples.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/LDAPExamples.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/PathExamples.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/SqlExamples.java
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/TestBean.java
Labels: java, run-default-scenario

#979 Activate propagation test for .NET
  tests/test_identify.py
  utils/build/docker/dotnet/Endpoints/IdentifyEndpoint.UserDetails.cs
Labels: run-default-scenario

#997 Skip PHP on newly added span sampling tests
  parametric/test_span_sampling.py
Labels: run-default-scenario

#990 Switch some tests to do sample override and drop decision maker
  parametric/test_headers_tracestate_dd.py
Labels: run-default-scenario

#983 remove python test skips for padding
  parametric/test_headers_b3.py
  parametric/test_headers_b3multi.py
Labels: run-default-scenario

#957 Add parametric tests of the 'Supporting 128-Bit TraceIds' RFC
  parametric/test_128_bit_traceids.py
Labels: run-default-scenario

#996 remove python tracer skip for test_tracestate_ows_handling
  parametric/test_headers_tracecontext.py
Labels: run-default-scenario

#1014 Update dependencies for grpc and protobuf
  parametric/requirements.txt
Labels: run-default-scenario

#1008 Add binary path support
  utils/build/build.sh
  utils/build/docker/dotnet/install_ddtrace.sh
Labels: run-default-scenario

#1011 Enable W3C tests for released Java Library v1.11.0
  parametric/apps/java/pom.xml
  parametric/test_headers_b3.py
  parametric/test_headers_b3multi.py
  parametric/test_headers_datadog.py
  parametric/test_headers_precedence.py
  parametric/test_headers_tracecontext.py
  parametric/test_headers_tracestate_dd.py
Labels: run-default-scenario

#1017 Skipped OTel parametric tests for Go
  parametric/test_otel_span_methods.py
  parametric/test_otel_span_with_w3c.py
  parametric/test_otel_tracer.py
Labels: run-default-scenario

#1009 update ddtrace + grpcio + grpcio-tools + protobuf
  parametric/requirements.txt
Labels: run-default-scenario

#1003 Allow easier Ruby local testing
  parametric/README.md
  parametric/apps/ruby/Gemfile
  parametric/apps/ruby/README.md
  parametric/conftest.py
Labels: run-default-scenario

#828 Enable test_identify for Python
  tests/test_identify.py
Labels: python

#955 [parametric] Fix remaining dotnet w3c tracecontext header tests
  parametric/apps/dotnet/ApmTestClient.csproj
  parametric/apps/dotnet/Program.cs
  parametric/apps/dotnet/Services/ApmTestClientService.cs
  parametric/test_headers_tracecontext.py
  parametric/test_headers_tracestate_dd.py
Labels: run-default-scenario

#1027 [parametric] Update Java client
  parametric/README.md
  parametric/apps/java/build.sh
  parametric/apps/java/pom.xml
  parametric/apps/java/run.sh
  parametric/apps/java/src/main/java/com/datadoghq/ApmClientImpl.java
  parametric/apps/java/src/main/java/com/datadoghq/App.java
  parametric/conftest.py
Labels: java

#1020 ASM - Add a test for boolean options in WAF rules
  tests/appsec/waf/test_miscs.py
Labels: run-default-scenario
