Repository DataDog/system-tests, pull requests merged in 2023-06, with the labels that each got.

#1225 improve suspicious request blocking test on uri raw
  tests/appsec/blocking_rule.json
  tests/appsec/test_blocking_addresses.py
Labels: run-default-scenario

#1229 Skip broken 128 test for golang until fix is merged there
  parametric/test_128_bit_traceids.py
Labels: run-default-scenario

#1228 Added a Readme to apm_tracing_e2e with running instructions
  docs/execute/e2e.md
  tests/apm_tracing_e2e/README.md
Labels: run-default-scenario

#1245 Upgrade java version for parametric tests
  tests/parametric/conftest.py
  utils/build/docker/java/parametric/Dockerfile
  utils/build/docker/java/parametric/run.sh
Labels: run-default-scenario

#1189 lib-injection: add inject all test cases
  .github/workflows/experimental.yml
  lib-injection/build/docker/all/config.yaml
  lib-injection/build/docker/all/values-override.yaml
  lib-injection/run-auto-lib-injection.sh
  lib-injection/src/test/shell/functions.sh
Labels: run-default-scenario

#1231 [parametric/dotnet] prepare auto-instrumentation and other code clean-up, redux
  .gitignore
  tests/parametric/conftest.py
  utils/build/docker/dotnet/parametric/.dockerignore
  utils/build/docker/dotnet/parametric/.gitignore
  utils/build/docker/dotnet/parametric/ApmTestClient.csproj
  utils/build/docker/dotnet/parametric/Dockerfile
  utils/build/docker/dotnet/parametric/Program.cs
  utils/build/docker/dotnet/parametric/Protos/apm_test_client.proto
  utils/build/docker/dotnet/parametric/Services/ApmTestClientService.cs
Labels: run-default-scenario, dotnet

#1246 Rename TestOnboardingInstallBaseTest -> _OnboardingInstallBaseTest
  tests/onboarding/test_onboarding_install.py
Labels: run-default-scenario

#1244 Add vscode conf to run and debug default scenario
  .vscode/launch.json
  .vscode/settings.json
Labels: run-default-scenario

#1257 Add -p no:warnings for set of scenarios
  run.sh
Labels: run-default-scenario

#1224 Prepare nodejs Unvalidated redirect vulnerability testing
  tests/appsec/iast/sink/test_unvalidated_redirect.py
  utils/build/docker/nodejs/express4/iast/index.js
Labels: run-default-scenario

#1258 Update php install URL to latest
  utils/build/docker/php/parametric/install.sh
Labels: run-default-scenario

#1256 Parametric tests wait for number of spans instead of traces
  parametric/test_span_sampling.py
  tests/parametric/conftest.py
Labels: run-default-scenario

#1259 activate test headers in appsec waf for Python
  tests/appsec/waf/test_addresses.py
Labels: run-default-scenario

#1262 Remove gorilla weblog
  .github/workflows/ci.yml
  docs/CI/github-actions.md
  docs/execute/build.md
  tests/test_semantic_conventions.py
  tests/test_standard_tags.py
  utils/build/docker/golang/app/go.mod
  utils/build/docker/golang/app/go.sum
  utils/build/docker/golang/app/gorilla.go
  utils/build/docker/golang/gorilla.Dockerfile
Labels: run-default-scenario

#1218 Suspicious request blocking tests for Java
  tests/appsec/test_blocking_addresses.py
  utils/build/docker/java/jersey-grizzly2/pom.xml
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
  utils/build/docker/java/ratpack/pom.xml
  utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
  utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/WafPostHandler.java
  utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
  utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
Labels: java, test_the_tests

#1249 [parametric/dotnet] add gRPC endpoints for OpenTelemetry API tests
  parametric/test_otel_span_methods.py
  parametric/test_otel_span_with_w3c.py
  parametric/test_otel_tracer.py
  tests/parametric/conftest.py
  utils/build/docker/dotnet/parametric/ApmTestClient.csproj
  utils/build/docker/dotnet/parametric/Dockerfile
  utils/build/docker/dotnet/parametric/DuckTypes/IDuckSpanContext.cs
  utils/build/docker/dotnet/parametric/Protos/apm_test_client.proto
  utils/build/docker/dotnet/parametric/Services/ApmTestClientService.Common.cs
  utils/build/docker/dotnet/parametric/Services/ApmTestClientService.Otel.cs
  utils/build/docker/dotnet/parametric/Services/ApmTestClientService.cs
  utils/parametric/protos/apm_test_client.proto
Labels: run-default-scenario, dotnet

#1251 onboarding agent script auto install
  .gitlab-ci.yml
  tests/onboarding/autoinjection/lang/python_install.sh
  tests/onboarding/autoinjection/repositories/autoinstall/execute_install_script_dev.sh
  tests/onboarding/infra_provision/includes/provision_init_config.yml
  tests/onboarding/infra_provision/includes/provision_installation_checks.yml
  tests/onboarding/infra_provision/includes/provision_prepare_docker.yml
  tests/onboarding/infra_provision/provision_AIT-6447.yml
  tests/onboarding/infra_provision/provision_onboarding_ansible_host.yml
  tests/onboarding/infra_provision/provision_onboarding_container.yml
  tests/onboarding/infra_provision/provision_onboarding_host.yml
  tests/onboarding/infra_provision/provision_onboarding_host_container.yml
  tests/onboarding/test_onboarding_install.py
  tests/onboarding/weblog/java/test-app-java/test-app-java_run.sh
  utils/_context/_scenarios.py
  utils/_context/virtual_machines.py
  utils/onboarding/backend_interface.py
  utils/onboarding/provision_utils.py
Labels: run-default-scenario

#1264 cleanup old decorators
  tests/appsec/test_reports.py
Labels: run-default-scenario

#1267 Allow @released only on classes
  tests/appsec/test_ip_blocking_full_denylist.py
  tests/appsec/waf/test_blocking.py
  tests/test_the_test/test_decorators.py
  utils/_decorators.py
Labels: run-default-scenario

#1260 [ASM] activate tests for newly minted features
  tests/appsec/blocking_rule.json
  tests/appsec/test_blocking_addresses.py
  utils/build/docker/dotnet/Controllers/TagValueController.cs
Labels: dotnet

#1270 Add a way to force a test execution #913
  conftest.py
  docs/edit/egg-chicken-changes.md
  docs/execute/force-execute.md
Labels: run-default-scenario

#1273 Optimize CI
  .github/actions/install_runner/action.yaml
  .github/actions/lint_code/action.yaml
  .github/workflows/ci.yml
Labels: run-default-scenario

#1282 Fix fuzzer CI
  .github/workflows/ci.yml
Labels: run-default-scenario

#1279 migrate parametric tests
  .github/workflows/parametric.yml
  parametric/conftest.py
  parametric/run.sh
  parametric/test_128_bit_traceids.py
  parametric/test_headers_b3.py
  parametric/test_headers_b3multi.py
  parametric/test_headers_datadog.py
  parametric/test_headers_none.py
  parametric/test_headers_precedence.py
  parametric/test_headers_tracecontext.py
  parametric/test_headers_tracestate_dd.py
  parametric/test_library_tracestats.py
  parametric/test_otel_span_methods.py
  parametric/test_otel_span_with_w3c.py
  parametric/test_otel_tracer.py
  parametric/test_partial_flushing.py
  parametric/test_span_sampling.py
  parametric/test_tracer.py
  tests/parametric/README.md
  tests/parametric/conftest.py
  tests/parametric/test_128_bit_traceids.py
  tests/parametric/test_headers_b3.py
  tests/parametric/test_headers_b3multi.py
  tests/parametric/test_headers_datadog.py
  tests/parametric/test_headers_none.py
  tests/parametric/test_headers_precedence.py
  tests/parametric/test_headers_tracecontext.py
  tests/parametric/test_headers_tracestate_dd.py
  tests/parametric/test_library_tracestats.py
  tests/parametric/test_otel_span_methods.py
  tests/parametric/test_otel_span_with_w3c.py
  tests/parametric/test_otel_tracer.py
  tests/parametric/test_partial_flushing.py
  tests/parametric/test_span_sampling.py
  utils/scripts/parametric/generate_protos.ps1
  utils/scripts/parametric/generate_protos.sh
  utils/scripts/parametric/run_reference_http.sh
Labels: run-default-scenario

#1285 Make parametric tests concurrent again
  run.sh
Labels: run-default-scenario

#1281 Add IAST unvalidated redirect vertx enpoints
  tests/appsec/iast/sink/test_unvalidated_redirect.py
  tests/appsec/iast/sink/test_unvalidated_redirect_forward.py
  utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
  utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
Labels: java, run-default-scenario

#1290 Skip flaky test on java
  tests/test_telemetry.py
Labels: run-default-scenario

#1298 parametric: update go tracer and enable new 128bit test case
  tests/parametric/test_128_bit_traceids.py
  utils/build/docker/golang/parametric/go.mod
  utils/build/docker/golang/parametric/go.sum
Labels: run-default-scenario

#1301 Reduce flakiness on span sampling tests.
  tests/parametric/test_span_sampling.py
Labels: run-default-scenario

#1320 Late pulumi import: improve pytest performance
  utils/_context/_scenarios.py
  utils/_context/virtual_machines.py
Labels: run-all-scenarios

#1311 Increase sampling threshold, reduce request count #1210
  .github/workflows/ci.yml
  .github/workflows/compute-scenarios.yml
  tests/test_sampling_rates.py
  utils/interfaces/_library/core.py
  utils/interfaces/_library/sampling.py
Labels: run-sampling-scenario

#1315 Improve test for telemetry heartbeats
  tests/test_telemetry.py
Labels: run-default-scenario

#1284 Automated user events milestone 0
  docs/weblog/README.md
  tests/appsec/test_automated_login_events.py
  utils/build/docker/nodejs/express4/app.js
  utils/build/docker/nodejs/express4/auth.js
  utils/build/docker/nodejs/express4/package-lock.json
  utils/build/docker/nodejs/express4/package.json
Labels: run-default-scenario

#1312 Fix observer in scenarios
  utils/_context/_scenarios.py
Labels: run-open-telemetry-scenarios

#1295 Parametric log outputs
  tests/parametric/conftest.py
Labels: run-default-scenario

#1313 go: enable exclusion filters tests
  tests/appsec/waf/test_exclusions.py
Labels: run-all-scenarios

#1326 Deserialize in proxy
  .github/actions/pull_images/action.yml
  .github/workflows/ci.yml
  .github/workflows/compute-scenarios.yml
  .github/workflows/update-agent-protobuf.yml
  requirements.txt
  utils/_context/containers.py
  utils/build/build.sh
  utils/build/docker/proxy.Dockerfile
  utils/interfaces/_core.py
  utils/proxy/_decoders/protobuf_schemas.py
  utils/proxy/_decoders/trace_payload.descriptor
  utils/proxy/_deserializer.py
  utils/proxy/core.py
Labels: run-all-scenarios, run-open-telemetry-scenarios

#1248 Increase max denylist size in the full_denylist scenarios
  tests/appsec/blocking_rule.json
  tests/appsec/rc_expected_requests_block_full_denylist_asm_data.json
  tests/appsec/test_blocking_addresses.py
  tests/appsec/test_ip_blocking_full_denylist.py
  tests/appsec/test_user_blocking_full_denylist.py
  utils/proxy/rc_mocked_responses_asm_data_full_denylist.json
Labels: run-all-scenarios
