Repository DataDog/system-tests, pull requests merged in 2023-04, with the labels that each got.

#999 [dotnet library] activate headers tag config test
  tests/test_library_conf.py
Labels: run-default-scenario

#1006 Parametric: Add more tests for 128-bit TraceId support.
  parametric/test_128_bit_traceids.py
Labels: run-default-scenario

#1034 Pin ruby images with 3.1.3
  lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails-bundle-deploy/Dockerfile
  lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails-conflict/Dockerfile
  lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails-explicit/Dockerfile
  lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails-gemsrb/Dockerfile
  lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails/Dockerfile
Labels: run-default-scenario

#1025 chore(python): add python (flask and django) sql injection system tests
  tests/appsec/iast/sink/test_iast_sql_injection.py
  tests/appsec/iast/sink/test_iast_weak_hash.py
  utils/build/docker/python/django/django.app.urls.py
  utils/build/docker/python/flask/app.py
Labels: python

#1001 Update instrumentation telemetry tests for golang
  tests/test_telemetry.py
Labels: run-default-scenario

#1037 skip failing test on python
  tests/appsec/iast/sink/test_iast_sql_injection.py
  tests/appsec/iast/sink/test_iast_weak_hash.py
Labels: run-default-scenario

#1038 chore(python): update tracer version in iast tests
  tests/appsec/iast/sink/test_iast_sql_injection.py
  tests/appsec/iast/sink/test_iast_weak_hash.py
Labels: python

#1045 Upgrade Java builder image to 3.9-eclipse-temurin-11
  utils/build/docker/java/jersey-grizzly2.Dockerfile
  utils/build/docker/java/ratpack.Dockerfile
  utils/build/docker/java/resteasy-netty3.Dockerfile
  utils/build/docker/java/spring-boot-jetty.Dockerfile
  utils/build/docker/java/spring-boot-openliberty.Dockerfile
  utils/build/docker/java/spring-boot-undertow.Dockerfile
  utils/build/docker/java/spring-boot-wildfly.Dockerfile
  utils/build/docker/java/spring-boot.Dockerfile
  utils/build/docker/java/uds-spring-boot.Dockerfile
  utils/build/docker/java/vertx3.Dockerfile
Labels: java, run-default-scenario

#1043 Remove repo.spring.io
  utils/build/docker/java/spring-boot-native.Dockerfile
  utils/build/docker/java/spring-boot/pom.xml
Labels: java, run-default-scenario

#1046 Use buildx throughout
  utils/build/build.sh
Labels: run-default-scenario

#1052 Ignore additional files
  .gitignore
Labels: run-default-scenario

#1057 Skip failing test on python
  tests/appsec/iast/sink/test_iast_sql_injection.py
  tests/appsec/iast/sink/test_iast_weak_hash.py
Labels: run-default-scenario

#1049 fix(parametric-test): update test_otel_get_span_context
  parametric/test_otel_span_methods.py
Labels: run-default-scenario

#1035 [dotnet library] remove some bug tags
  tests/appsec/waf/test_rules.py
Labels: run-default-scenario

#935 aditi.maheshwari/telemetry app-started product and configuration test
  tests/test_telemetry.py
Labels: run-default-scenario

#1060 IAST python version fix
  tests/appsec/iast/sink/test_iast_sql_injection.py
  tests/appsec/iast/sink/test_iast_weak_hash.py
  utils/interfaces/_library/appsec_iast.py
Labels: run-default-scenario

#1061 paramteric(otel): update set attributes test
  parametric/test_otel_span_methods.py
Labels: run-default-scenario

#1013 enable 128-bit trace id tests for node
  parametric/test_128_bit_traceids.py
Labels: run-default-scenario

#1065 Fix typos
  tests/test_telemetry.py
  utils/interfaces/_library/core.py
  utils/interfaces/_library/sampling.py
Labels: run-default-scenario

#1068 chore(python): fix reported path
  tests/appsec/iast/sink/test_iast_weak_hash.py
Labels: run-default-scenario

#1005 [parametric] For dotnet, unskip the dotnet test case that tests the decision maker reset
  parametric/apps/dotnet/ApmTestClient.csproj
  parametric/test_headers_tracestate_dd.py
Labels: run-default-scenario

#1066 parametric: Add some smoke tests for partial flushing support
  parametric/README.md
  parametric/conftest.py
  parametric/test_partial_flushing.py
Labels: run-default-scenario

#991 Add Django Events SDK support
  tests/appsec/test_event_tracking.py
  utils/build/docker/python/django/django.app.urls.py
  utils/build/docker/python/flask/app.py
Labels: python

#1072 add suspicious requests tests
  tests/appsec/test_blocking_addresses.py
Labels: run-default-scenario

#1073 parametric: use python3.9 binary if available
  parametric/run.sh
Labels: run-default-scenario

#1051 Fix docker build including logs_* in context
  .dockerignore
Labels: run-default-scenario

#1081 Fix spring-boot-wildfly build
  utils/build/docker/java/spring-boot/pom.xml
Labels: java, run-default-scenario

#1080 Fix test name for IAST request body
  tests/appsec/iast/source/test_iast_request_body.py
Labels: run-default-scenario

#1079 Enable all supported IAST tests for Java
  tests/appsec/iast/sink/test_iast_command_injection.py
  tests/appsec/iast/sink/test_iast_ldap_injection.py
  tests/appsec/iast/sink/test_iast_path_traversal.py
  tests/appsec/iast/sink/test_iast_sql_injection.py
  tests/appsec/iast/sink/test_iast_weak_cipher.py
  tests/appsec/iast/sink/test_iast_weak_hash.py
  tests/appsec/iast/source/test_iast_request_body.py
  tests/appsec/iast/source/test_iast_request_cookie_name.py
  tests/appsec/iast/source/test_iast_request_cookie_value.py
  tests/appsec/iast/source/test_iast_request_header.py
  tests/appsec/iast/source/test_iast_request_header_name.py
  tests/appsec/iast/source/test_iast_request_parameter.py
  tests/appsec/iast/source/test_iast_request_parameter_name.py
Labels: run-default-scenario

#1082 Revert "parametric: use python3.9 binary if available (#1073)"
  parametric/run.sh
Labels: run-default-scenario

#1024 Enable IP Blocking tests for Python
  tests/appsec/test_ip_blocking.py
Labels: python

#1070 [Telemetry] Unskip tests that should no longer be flaky
  tests/test_telemetry.py
Labels: run-default-scenario

#1062 parametric(otel): remove new_root from start span
  parametric/_library_client.py
  parametric/apps/golang/apm_test_client.pb.go
  parametric/apps/golang/otel.go
  parametric/apps/python/apm_test_client/protos/apm_test_client_pb2.py
  parametric/apps/python/apm_test_client/protos/apm_test_client_pb2_grpc.py
  parametric/protos/apm_test_client.proto
  parametric/protos/apm_test_client_pb2.py
  parametric/test_otel_span_methods.py
  parametric/test_otel_span_with_w3c.py
  parametric/test_otel_tracer.py
Labels: run-default-scenario

#1058 parametric(otel): add tests for setting service names on spans
  parametric/test_otel_span_methods.py
Labels: run-default-scenario

#1059 parametric(6to7): run 128 bit trace id tests with python app
  parametric/test_128_bit_traceids.py
Labels: run-default-scenario

#1083 Fix Flask view without response
  utils/build/docker/python/flask/app.py
Labels: bug

#1096 Doc on requirements
  README.md
  docs/execute/README.md
  docs/execute/requirements.md
Labels: run-default-scenario

#1053 Add watch script
  .github/workflows/lint.yml
  .shellcheck
  .shellcheckrc
  shell.nix
  utils/scripts/shellcheck.sh
  utils/scripts/watch.sh
Labels: run-default-scenario

#1095 Improve nix environment
  requirements.txt
  run.sh
  shell.nix
  utils/_context/containers.py
  utils/build/build.sh
Labels: run-default-scenario

#1099 Improve PR template
  .github/pull_request_template.md
Labels: run-default-scenario

#1100 fix dotnet docker base images
  utils/build/docker/dotnet/install_ddtrace.sh
  utils/scripts/docker_base_image.sh
Labels: run-default-scenario

#1097 parametric(otel): fix TypeError raised in test_otel_set_attributes_different_types
  parametric/test_otel_span_methods.py
Labels: run-default-scenario

#1108 [parametric] bump go tracer and unskip w3c reset dm testcase
  parametric/apps/golang/go.mod
  parametric/apps/golang/go.sum
  parametric/test_headers_tracestate_dd.py
Labels: run-default-scenario

#1107 Remove FleetManagment test class
  tests/appsec/test_conf.py
Labels: run-default-scenario

#1090 Update CODEOWNERS with @DataDog/system-tests-core
  .github/CODEOWNERS
Labels: run-default-scenario

#1113 Move apt-get install socat to uds weblog
  utils/build/docker/dotnet/uds.Dockerfile
  utils/build/docker/golang/uds-echo.Dockerfile
  utils/build/docker/java/uds-spring-boot.Dockerfile
  utils/build/docker/python/uds-flask.Dockerfile
  utils/build/docker/set-system-tests-weblog-env.Dockerfile
Labels: run-default-scenario

#1015 parametric(otel): run opentelemetry tests with python app
  parametric/_library_client.py
  parametric/apps/python/apm_test_client/server.py
  parametric/apps/python_http/apm_test_client/server.py
  parametric/conftest.py
  parametric/test_otel_span_methods.py
  parametric/test_otel_span_with_w3c.py
  parametric/test_otel_tracer.py
Labels: run-default-scenario

#1115 Tracer does not support latest version of flask
  utils/_context/containers.py
  utils/build/docker/python/flask-poc.Dockerfile
  utils/build/docker/python/uds-flask.Dockerfile
  utils/build/docker/python/uwsgi-poc.Dockerfile
Labels: run-default-scenario

#1116 [dotnet asm] active url & static rule tests
  README.md
  docs/execute/requirements.md
  tests/appsec/test_conf.py
  tests/test_scrubbing.py
Labels: run-default-scenario

#1128 Show requests/response in log on failure
  conftest.py
  utils/_context/_scenarios.py
  utils/_weblog.py
Labels: dev-x
