Repository DataDog/system-tests, pull requests merged in 2023-02, with the labels that each got.

#813 [ASM] Fix test_multiple_matching_substring test for dotnet
  tests/test_standard_tags.py
Labels: bug

#875 Build labels
  .github/workflows/ci.yml
Labels: run-default-scenario

#874 Event tracking for Java
  tests/appsec/test_event_tracking.py
  utils/build/docker/java/jersey-grizzly2/pom.xml
  utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
  utils/build/docker/java/ratpack/pom.xml
  utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
  utils/build/docker/java/resteasy-netty3/pom.xml
  utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
  utils/build/docker/java/spring-boot-3-native/src/main/java/com/datadoghq/springbootnative/WebController.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
  utils/build/docker/java/vertx3/pom.xml
  utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
Labels: java

#897 Fix typo in Java build file for adding external binaries to class path
  parametric/apps/java/pom.xml
Labels: run-default-scenario

#899 Update parametric tests java client to use global proto
  parametric/apps/java/pom.xml
  parametric/apps/java/src/main/java/com/datadoghq/ApmClientImpl.java
  parametric/apps/java/src/main/proto/apm_test_client.proto
  parametric/protos/apm_test_client.proto
Labels: java, run-default-scenario

#898 [apm] manually index spans without manual retention filter
  docs/weblog/README.md
  tests/apm_tracing_e2e/test_single_span.py
  utils/build/docker/golang/app/chi.go
  utils/build/docker/golang/app/common.go
  utils/interfaces/_backend.py
Labels: run-default-scenario

#904 fix: retrieve IP in a more reliable way for Python IP tests
  tests/appsec/test_reports.py
Labels: bug, python

#901 Add django and flask endpoints for the user blocking test
  utils/build/docker/python/django/django.app.urls.py
  utils/build/docker/python/flask/app.py
Labels: python, run-default-scenario

#907 [apm] Enable APM E2E Single Span tests for Java spring-boot
  run.sh
  tests/apm_tracing_e2e/test_single_span.py
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
Labels: run-default-scenario

#902 Fix parametric Java client docker build
  parametric/apps/java/build.sh
  parametric/apps/java/pom.xml
  parametric/conftest.py
Labels: java

#917 [apm-e2e] rewording and improvements to the EvP API
  tests/apm_tracing_e2e/test_single_span.py
  utils/interfaces/_backend.py
Labels: run-default-scenario
