Repository DataDog/system-tests, pull requests merged in 2025-08, with the labels that each got.

#5005 enable python flares tests
  manifests/python.yml
Labels: python

#5084 [SINT-3848] 🔒 Pin GitHub Actions to specific SHA versions for enhanced security
  .github/workflows/ci.yml
  .github/workflows/compute-impacted-libraries.yml
  .github/workflows/compute-scenarios.yml
  .github/workflows/compute-workflow-parameters.yml
  .github/workflows/lint.yml
  .github/workflows/run-docker-mode.yml
  .github/workflows/run-end-to-end.yml
  .github/workflows/run-exotics.yml
  .github/workflows/run-external-processing.yml
  .github/workflows/run-lib-injection.yml
  .github/workflows/run-parametric.yml
  .github/workflows/system-tests.yml
  .github/workflows/update-agent-protobuf.yml
Labels: mergequeue-status: waiting

#4797 Enable docker_ssi/test_instrumentation_source_ssi test for PHP
  docs/scenarios/docker_ssi.md
  manifests/php.yml
  tests/docker_ssi/test_docker_ssi.py
  utils/build/ssi/php/php-app.Dockerfile
Labels: mergequeue-status: in_progress
