Repository DataDog/system-tests, pull requests merged in 2025-07, with the labels that each got.

#4892 [php] Download dev artifacts from s3
  manifests/php.yml
  utils/scripts/load-binary.sh
Labels: mergequeue-status: waiting

#4957 [APISec] Fix API Sec priority when schema is present
  manifests/dotnet.yml
  tests/appsec/test_asm_standalone.py
Labels: bug

#4992 [python] make sure that xmltodict is installed for fastapi
  utils/build/build_python_base_images.sh
  utils/build/docker/python/django-poc.Dockerfile
  utils/build/docker/python/django-poc.base.Dockerfile
  utils/build/docker/python/django-py3.13.Dockerfile
  utils/build/docker/python/django-py3.13.base.Dockerfile
  utils/build/docker/python/fastapi.Dockerfile
  utils/build/docker/python/fastapi.base.Dockerfile
  utils/build/docker/python/flask-poc.Dockerfile
  utils/build/docker/python/flask-poc.base.Dockerfile
  utils/build/docker/python/python3.12.Dockerfile
  utils/build/docker/python/python3.12.base.Dockerfile
  utils/build/docker/python/uds-flask.Dockerfile
  utils/build/docker/python/uwsgi-poc.Dockerfile
  utils/build/docker/python/uwsgi-poc.base.Dockerfile
Labels: build-python-base-images
