Repository DataDog/system-tests, pull requests merged in 2025-04, with the labels that each got.

#4442 add data_jobs_openlineage_enabled to telemetry config rules
  utils/telemetry/intake/static/jvm_config_rules.json
Labels: mergequeue-status: rejected

#4429 [python] enable span events testing for python flask app
  manifests/python.yml
  tests/test_span_events.py
  utils/build/docker/python/flask-poc.Dockerfile
  utils/build/docker/python/flask/app.py
Labels: build-python-base-images

#4491 Add CI Visibility scalatest fork monitor telemetry config rule
  utils/telemetry/intake/static/jvm_config_rules.json
Labels: mergequeue-status: rejected

#4492 [PHP] Enable k8s_lib_injection tests
  .gitlab-ci.yml
  docs/scenarios/k8s_lib_injection.md
  lib-injection/build/build_lib_injection_images.sh
  lib-injection/build/docker/php/dd-lib-php-init-test-app/Dockerfile
  lib-injection/build/docker/php/dd-lib-php-init-test-app/build.sh
  lib-injection/build/docker/php/dd-lib-php-init-test-app/index.php
  manifests/php.yml
  utils/_context/_scenarios/k8s_lib_injection.py
  utils/k8s_lib_injection/k8s_datadog_kubernetes.py
  utils/k8s_lib_injection/k8s_weblog.py
  utils/scripts/ci_orchestrators/k8s_ssi.json
  utils/scripts/ssi_wizards/common_wizard_functions.sh
  utils/scripts/ssi_wizards/k8s_ssi_wizard.sh
Labels: mergequeue-status: rejected

#4044 Protobuf system test for schema tracking
  docs/edit/add-new-test.md
  docs/weblog/README.md
  manifests/cpp_httpd.yml
  manifests/cpp_nginx.yml
  manifests/dotnet.yml
  manifests/golang.yml
  manifests/java.yml
  manifests/nodejs.yml
  manifests/php.yml
  manifests/python.yml
  manifests/ruby.yml
  tests/test_protobuf.py
  utils/_features.py
  utils/build/docker/common/message.proto
  utils/build/docker/dotnet/install_ddtrace.sh
  utils/build/docker/dotnet/weblog/Endpoints/ProtobufEndpoint.cs
  utils/build/docker/dotnet/weblog/Models/Message.cs
  utils/build/docker/dotnet/weblog/app.csproj
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
  utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/proto_message/Message.java
Labels: java, dotnet

#4131 [java] Enable code origin test for java
  tests/debugger/test_debugger_probe_snapshot.py
Labels: enhancement, java

#4568 [python] enable 3.13 for prod
  utils/scripts/ci_orchestrators/workflow_data.py
Labels: python

#4560 revert TestCommandInjection bug
  manifests/python.yml
  tests/appsec/iast/sink/test_command_injection.py
  utils/build/docker/python/django/app/urls.py
  utils/build/docker/python/fastapi/main.py
  utils/build/docker/python/flask/app.py
Labels: python
